#!/usr/bin/env bash
# generate-gog-completions.sh — Generate native zsh completions for gogcli (gog)
#
# Reads the full command schema from `gog help-json` and emits a _gog
# completion file to stdout.  The output uses native zsh completion
# functions (_arguments, _describe) instead of the bashcompinit shim
# that `gog completion zsh` produces.
#
# Usage:
#   bash generate-gog-completions.sh > _gog
#   cp _gog /usr/local/share/zsh/site-functions/_gog   # Linux
#   cp _gog /opt/homebrew/share/zsh/site-functions/_gog # macOS
#
# Requirements: gog, jq
set -euo pipefail

command -v gog >/dev/null 2>&1 || { echo "ERROR: gog not found in PATH" >&2; exit 1; }
command -v jq  >/dev/null 2>&1 || { echo "ERROR: jq not found in PATH" >&2; exit 1; }

SCHEMA=$(gog help-json 2>/dev/null)
GOG_VERSION=$(echo "$SCHEMA" | jq -r '.build')

# Write jq filter to temp file (avoids bash quoting issues)
JQ_FILTER=$(mktemp)
trap 'rm -f "$JQ_FILTER"' EXIT

cat > "$JQ_FILTER" <<'JQEOF'
# Escape special chars for zsh completion strings
def zsh_escape:
  gsub("'"; "'\\''")
  | gsub("\\["; "\\[")
  | gsub("\\]"; "\\]");

# Build _arguments flag spec from a flag object
# Uses zsh brace expansion for short+long pairs:
#   '(-f --flag)'{-f,--flag}'[help]'          (bool)
#   '(-f --flag)'{-f,--flag}'=[help]:value: '  (string)
def flag_spec:
  (if (.type == "bool" or .type == "*bool" or
       .type == "kong.helpFlag" or .type == "kong.VersionFlag")
   then false else true end) as $takes_arg |
  ((.help // "") | split("\n")[0] | zsh_escape) as $help |
  (.short // "") as $short |
  if $takes_arg then
    if $short != "" then
      "'(-\($short) --\(.name))'{-\($short),--\(.name)}'=[\($help)]:value: '"
    else
      "'--\(.name)=[\($help)]:value: '"
    end
  else
    if $short != "" then
      "'(-\($short) --\(.name))'{-\($short),--\(.name)}'[\($help)]'"
    else
      "'--\(.name)[\($help)]'"
    end
  end;

# Recursively emit completion functions for a command node
def emit($prefix; $path):
  if (.subcommands // [] | length) > 0 then
    # Commands list function
    "\($prefix)_commands() {\n    local -a commands=(\n" +
    ([.subcommands[] |
      "        '\(.name):\((.help // "") | split("\n")[0] | zsh_escape)'"
    ] | join("\n")) +
    "\n    )\n    _describe \"command\" commands\n}\n\n" +

    # Main dispatch function
    "\($prefix)() {\n    local context state state_descr line\n    typeset -A opt_args\n\n    _arguments -C \\\n" +
    ([(.flags // [])[] | "        \(flag_spec)"] | join(" \\\n")) +
    (if ((.flags // []) | length) > 0 then " \\\n" else "" end) +
    "        \"1:command:\($prefix)_commands\" \\\n" +
    "        \"*::arg:->args\"\n\n" +
    "    case $state in\n        args)\n            case $words[1] in\n" +
    ([.subcommands[] |
      ([.name] + (.aliases // [])) as $pats |
      "                \($pats | join("|"))) \($prefix)_\(.name | gsub("-"; "_")) ;;"
    ] | join("\n")) +
    "\n            esac\n            ;;\n    esac\n}\n\n" +

    # Recurse into each subcommand
    ([.subcommands[] |
      emit("\($prefix)_\(.name | gsub("-"; "_"))"; "\($path) \(.name)")
    ] | join(""))

  else
    # Leaf command — flags only
    "\($prefix)() {\n    _arguments \\\n" +
    ([(.flags // [])[] | "        \(flag_spec)"] | join(" \\\n")) +
    (if ((.flags // []) | length) > 0 then " \\\n" else "" end) +
    "        \"*:file:_files\"\n}\n\n"
  end;

.command | emit("_gog"; "gog")
JQEOF

# ── Emit the completion file ──────────────────────────────────────
cat <<HEADER
#compdef gog

# Native zsh completions for gogcli (gog) — Google Workspace CLI
# Auto-generated by generate-gog-completions.sh
# gog version: ${GOG_VERSION}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Do not edit manually — regenerate with:
#   bash configs/generate-gog-completions.sh > configs/_gog

HEADER

echo "$SCHEMA" | jq -r -f "$JQ_FILTER"

cat <<'FOOTER'
_gog "$@"
FOOTER
