lastChangelogVersion: 15.6.2
modelRoles:
  default: anthropic/claude-opus-4-6
symbolPreset: nerd
statusLine:
  separator: powerline
  preset: xcsh
colorBlindMode: false
hideThinkingBlock: true
autoResume: true
autocompleteMaxVisible: 10
collapseChangelog: true
stt:
  enabled: true
compaction:
  idleEnabled: true
  handoffSaveToDisk: true
memories:
  enabled: true
todo:
  eager: true
renderMermaid:
  enabled: true
calc:
  enabled: true
inspect_image:
  enabled: true
github:
  enabled: true
