lastChangelogVersion: 14.0.3
modelRoles:
  default: anthropic/claude-opus-4-6
symbolPreset: nerd
statusLine:
  separator: slash
  preset: minimal
colorBlindMode: false
hideThinkingBlock: true
autoResume: true
autocompleteMaxVisible: 10
collapseChangelog: true
stt:
  enabled: true
compaction:
  idleEnabled: true
memories:
  enabled: true
todo:
  eager: true
renderMermaid:
  enabled: true
calc:
  enabled: true
inspect_image:
  enabled: true
github:
  enabled: true
